name: Clang-tidy review
on:
  pull_request:

jobs:
  build:
    name: Clang tidy review
    runs-on: ubuntu-latest
    #container: zephyrprojectrtos/ci:v0.26.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@master
        with:
          # The GitHub token (or a personal access token)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The path to the clang-tidy fixes generated previously
          clang_tidy_fixes: clang-tidy-result/fixes.yml
          # Optionally set the number of comments per review
          # to avoid GitHub API timeouts for heavily loaded
          # pull requests
          suggestions_per_comment: 10
          # Since we run this action inside a docker container, the path must be prefixed with /__w/
          #repo_path_prefix: '/__w/'
