on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'v*-branch'
  push:
    branches:
      - main
      - 'v*-branch'
    tags:
      - v*

name: Code coverage

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        path: ncs/nrf
        fetch-depth: 0
    - name: Install base dependencies
      working-directory: ncs
      run: |
        sudo apt-get update
        sudo apt install --fix-missing -y ninja-build gcc-multilib
        pip3 install -r nrf/scripts/requirements-base.txt
        pip3 install pyelftools
    - name: West init and update
      run: |
        cd ncs/nrf
        west init -l
        west update --narrow -o=--depth=1

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ncs/nrf