name: Rebase from ncs main

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rebase from main
        run: |
          git remote add  ncs https://github.com/nrfconnect/sdk-nrf
          git fetch ncs
          git rebase --ff ncs/main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
