name: Rebase from ncs main

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rebase from main
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "github-actions[bot]"
          git remote add  ncs https://github.com/nrfconnect/sdk-nrf
          git fetch ncs
          git rebase -Xours ncs/main

      - name: Check if changes were made
        run: |
          if [[ `git diff origin/main --exit-code` ]]; then
            echo "HAS_CHANGES=1" >> $GITHUB_ENV
          else
            echo "HAS_CHANGES=0" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.HAS_CHANGES == '1'
        uses: peter-evans/create-pull-request@v4
