name: Unit test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'v*-branch'
  push:
    branches:
      - main
      - 'v*-branch'
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  coderbyheart/fw-nrfconnect-nrf-docker:main

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt install -y lcov gcc-multilib

      - name: West init and update
        run: |
          cd ncs/nrf
          west init -l
          west update --narrow -o=--depth=1

      - name: Run unit tests with twister
        continue-on-error: true
        shell: bash
        run: |
          cd ncs/nrf
          source ../zephyr/zephyr-env.sh
          ../zephyr/scripts/twister -C -T . -p native_posix

      - name: 'Tar twister output'
        run: tar -cvf twister_out.tar ncs/nrf/twister-out/

      - name: Uploade twister output
        uses: actions/upload-artifact@v2
        with:
          name: twister-out
          path: twister_out.tar
