name: Unit test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'v*-branch'
  push:
    branches:
      - main
      - 'v*-branch'
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt install -y lcov gcc-multilib

      - name: West init and update
        run: |
          cd ncs/nrf
          west init -l
          west update --narrow -o=--depth=1

      - name: Run unit tests with twister
        uses: docker://coderbyheart/fw-nrfconnect-nrf-docker:main
        #continue-on-error: true
        with:
          args: pwd && ls
          #ls
          #cd ncs/nrf
          #source ../zephyr/zephyr-env.sh
          #../zephyr/scripts/twister -C -T . -p native_posix

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: twister-out/coverage.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          working-directory: ncs/nrf

      - name: 'Tar twister output'
        run: tar -cvf twister_out.tar ncs/nrf/twister-out/

      - name: Upload twister output
        uses: actions/upload-artifact@v2
        with:
          name: twister-out
          path: twister_out.tar

