name: Unit test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'v*-branch'
  push:
    branches:
      - main
      - 'v*-branch'
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt install -y lcov

      - name: West init and update
        uses: docker://nrfassettracker/nrfconnect-sdk:main
        with:
          args: bash -c "cd ncs/nrf && west init -l && west update --narrow -o=--depth=1"

        #run: |
        #  cd ncs/nrf
        #  west init -l
        #  west update --narrow -o=--depth=1

      - name: Run unit tests with twister
        uses: docker://nrfassettracker/nrfconnect-sdk:main
        continue-on-error: true
        with:
          args: bash -c "apt install -y lcov gcc-multilib && cd ncs/nrf && source ../zephyr/zephyr-env.sh && ../zephyr/scripts/twister -C -T ./applications/asset_tracker_v2/tests/debug_module/ -p native_posix"
          #ls
          #cd ncs/nrf
          #source ../zephyr/zephyr-env.sh
          #../zephyr/scripts/twister -C -T . -p native_posix

      #- name: Get code coverage summary
      # This does not work due to some path error. genhtml command fails with unable to access debug_module_event.h error.
      #  id: codecovsum
      #  shell: bash
      #  working-directory: ncs/nrf/
      #  run: |
      #    codecov=$(genhtml --rc lcov_branch_coverage=1 twister-out/coverage.info |tail -4)

      - name: Comment with code coverage in PR
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            Here is your code coverage summary.

            ```

            ${{ steps.codecovsum.outputs.codecov }}

            ```


      #- name: 'Tar twister output'
      #  run: tar -cvf twister_out.tar ncs/nrf/twister-out/

      #- name: Upload twister output
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: twister-out
      #    path: twister_out.tar

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ncs/nrf/twister-out/*.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          minimum-coverage: 90
          artifact-name: code-coverage-report
          working-directory: ncs/nrf



